name: multispace
channels:
- bioconda
- conda-forge
- defaults
- dongqingsun
dependencies:
#SNAKEFILE
- star ==2.7.10a
- subread ==2.0.1
- bedtools ==2.30.0
- trim-galore ==0.6.7
- snakemake ==7.8.2
- samtools>=1.10




#GENERAL
- python>=3.7
- numpy==1.21.5
- pandas=1.3.5
- pip
- scipy >=1.7.3
- h5py ==3.6.0 
- Jinja2 =3.1.2 
- pytables >=3.7.0
- setuptools
- matplotlib =3.5.1
- stridespatial
- bsmap =2.90
