package:
  name: multispace
  version: "0.0.1"
source:
  path: ../../
requirements:
  build:
    - python >=3.8
    - pip
    - numpy ==1.21.5
    - scipy >=1.7.3
    - h5py ==3.6.0 
    - Jinja2==3.1.2 
    - pytables >=3.7.0
    - pandas==1.3.5  
    - setuptools
    - snakemake =7.8.2
    - star =2.7.10a
    - subread =2.0.1
    - samtools >=1.10
    - bedtools =2.30.0
    - trim-galore =0.6.7
    - matplotlib==3.5.1
    - stridespatial
    - bsmap =2.90

  run:
    - python >=3.8
    - pip
    - numpy ==1.21.5
    - scipy >=1.7.3
    - h5py ==3.6.0 
    - Jinja2==3.1.2 
    - pytables >=3.7.0
    - pandas ==1.3.5  
    - setuptools
    - snakemake =7.8.2
    - star =2.7.10a
    - subread =2.0.1
    - samtools >=1.10
    - bedtools =2.30.0
    - trim-galore =0.6.7
    - matplotlib==3.5.1
    - stridespatial
    - bsmap =2.90

build:
  preserve_egg_dir: True

about:
  home: https://github.com/Changzhanhe/MultiSpace
  license: GPL-3.0
  summary: MultiSpace(Single-cell Multi Omics Analysis In Space) is a multi-omics pipeline integrated RNA Expression, DNA methylation and Chromatin Accessibility analysis built using snakemake.